# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/backend/**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreInstaller@0
  displayName: Install latest version of .NET Core (3.0.100-preview-010184)
  inputs:
    version: '3.0.100-preview-010184'

- task: DotNetCoreInstaller@0
  displayName: Install latest version of .NET Core (2.1.300)
  inputs:
    version: '2.1.300'

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: '**/backend/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    projects: '**/backend/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Run UnitTests
  inputs:
    command: 'test'
    projects: '**/backend/**/*.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude=[System.*]*%2c[xunit.*]*%2c[CSharpWars.Tests.*]*'

- task: PublishCodeCoverageResults@1
  displayName: 'publish coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '**/coverage.cobertura.xml'

- script: |
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.15
    ./reportgenerator "-reports:$(Build.SourcesDirectory)/src/backend/CSharpWars/CSharpWars.Tests/coverage.cobertura.xml" "-targetdir:results" "-reporttypes:HTMLInline;HTMLChart"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/src/backend/CSharpWars/CSharpWars.Tests/results'

- script: |
    dotnet publish ./src/backend/CSharpWars/CSharpWars.Web.Api --configuration "Release" --output ./src/backend/CSharpWars/CSharpWars.Web.Api/bin/Release/publish

- script: |
    dotnet publish ./src/backend/CSharpWars/CSharpWars.ScriptProcessor --configuration "Release" --output ./src/backend/CSharpWars/CSharpWars.ScriptProcessor/bin/Release/publish

- script: |
      cd ./src/backend/CSharpWars/CSharpWars.Web.Api
      docker build -t djohnnie/csharpwars-api .
      docker login -u $(dockerId) -p $(dockerPwd)
      docker push djohnnie/csharpwars-api

- script: |
      cd ./src/backend/CSharpWars/CSharpWars.ScriptProcessor
      docker build -t djohnnie/csharpwars-processor .
      docker login -u $(dockerId) -p $(dockerPwd)
      docker push djohnnie/csharpwars-processor
